### ISSUE TITLE
Creating a library

### ISSUE THREAD

**Issue by wkevwang** [andreamazz/GearRefreshControl#1]
This refresh control looks amazing! I love the way the gears are animated and the fluidity of the transition. If possible, could you make a library of this project? I would be very interested

**Comment by andreamazz** [comment]
Hi @Megasonic988 
I'll be happy to. I'll work on it in the next few days. Cheers

**Comment by andreamazz** [comment]
Checkout latest commit, I moved the refresh control in a separate view so it can be used freely. I'll add some customisation options (like the tint) and create a cocoapod in the next few days.

**Comment by andreamazz** [comment]
Ok, done, you'll find the library in the `GearRefreshControl` pod
