### ISSUE TITLE
how to build on my iPhone ?

### ISSUE THREAD

**Issue by liufsd** [andreamazz/GearRefreshControl#2]
Run it success on my simulator.But run crash on my iPhone .
dyld: Library not loaded: @rpath/Pods_GearAnimation.framework/Pods_GearAnimation
  Referenced from: /var/mobile/Containers/Bundle/Application/7C2B1BB8-A967-4E9A-B801-A81AC1E88EB1/GearAnimation.app/GearAnimation
  Reason: image not found
(lldb) 
How to fix it ?
Thanks.

**Comment by andreamazz** [comment]
Hi. There might be something wrong with your configuration, the sample project runs fine on both the simulator and the device. Can you provide a sample project showing the issue?

**Comment by liufsd** [comment]
Found the solution, in the target's General tab, there is an Embedded Binaries field, add framework there, and the crash is resolved.

Reference is here on Apple Developer Forum.

Thanks.

**Comment by andreamazz** [comment]
That's weird though, are you integrating the library with cocoapods or with carthage?

**Comment by liufsd** [comment]
But i do not know why Xcode did not copy libs when i build on my iPhone. 
May be case by Xcode 7 beta
