### ISSUE TITLE
Editable colors

### ISSUE THREAD

**Issue by alexbredy** [andreamazz/GearRefreshControl#3]
Nice library. Would it be possible to make the gear colors as well as the background color customizable?

Thanks

**Comment by andreamazz** [comment]
Hi @alexbredy 
Yes, it's definitely in my todo list, I just need to find some time to devote to this control. I'll make a note and hope to get some time to work on it later this week. I'll keep you posted.

**Comment by alexbredy** [comment]
Ciao @andreamazz. Thanks for your swift reply, looking forward.

**Comment by andreamazz** [comment]
Hi. Checkout latest commit for `gearTintColor`. 

Cheers
