### ISSUE TITLE
Swift 3 Support

### ISSUE THREAD

**Issue by alombard** [andreamazz/GearRefreshControl#7]
Hello - would it be possible to add Swift 3 support?

Cheers,

Andrew

**Comment by andreamazz** [comment]
Sure, I'll work on it in the next few days, I have a bit of catching up to do on all the other libs.

**Comment by alombard** [comment]
Awesome - thanks!  

Andrew

**Comment by andreamazz** [comment]
Done, check out version `1.0.0`

**Comment by alombard** [comment]
Thanks!  Will do :) Appreciate your efforts.
